project:
  name: qs-workshop
  regions:
  - us-east-1
tests:
  default:
    template: ./templates/master.template.yaml
    regions:
    - us-east-1

    
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      EmailAddress: "seongikh@amazon.com"
      KeyPairName: "kp-simplhug90app1-nvirgnia-20220128"
      WebserverCIDR: "0.0.0.0/0"
      QSS3KeyPrefix: "qs-workshop/"
      QSS3BucketRegion: "$[taskcat_current_region]"
      QSS3BucketName: "$[taskcat_autobucket]"

